"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import {
  Sparkles,
  Send,
  Pencil,
  RefreshCw,
  Paperclip,
  Image as ImageIcon,
  Smile,
  Clock,
  CheckCheck,
  Crown,
  Tag,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { cn } from "@/lib/utils"
import { getApiBaseUrl } from "@/lib/api"
import type { Inquiry, InquiryReply } from "@/lib/inquiries"

interface ConversationThreadProps {
  inquiry: Inquiry
}

function formatReplyTime(value: string) {
  const date = new Date(value)

  if (Number.isNaN(date.getTime())) {
    return value
  }

  return date.toLocaleString("ko-KR", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  })
}

function getErrorMessage(error: unknown, fallback: string) {
  return error instanceof Error ? error.message : fallback
}

export function ConversationThread({ inquiry }: ConversationThreadProps) {
  const lastAutoGeneratedInquiryIdRef = useRef<string | null>(null)
  const [isEditing, setIsEditing] = useState(false)
  const [draftText, setDraftText] = useState(inquiry.aiDraft ?? "")
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSending, setIsSending] = useState(false)
  const [isLoadingReplies, setIsLoadingReplies] = useState(true)
  const [hasGeneratedDraft, setHasGeneratedDraft] = useState(false)
  const [generateError, setGenerateError] = useState<string | null>(null)
  const [replyError, setReplyError] = useState<string | null>(null)
  const [savedReplies, setSavedReplies] = useState<InquiryReply[]>([])

  const handleGenerateDraft = useCallback(async () => {
    setIsGenerating(true)
    setGenerateError(null)

    try {
      const response = await fetch(`${getApiBaseUrl()}/api/inquiries/${inquiry.id}/ai-draft`, {
        method: "POST",
      })
      const result = (await response.json()) as { aiDraft?: string; message?: string }

      if (!response.ok || !result.aiDraft) {
        throw new Error(result.message || "AI 초안 생성에 실패했습니다.")
      }

      setDraftText(result.aiDraft)
      setHasGeneratedDraft(true)
    } catch (error) {
      setGenerateError(getErrorMessage(error, "AI 초안 생성에 실패했습니다."))
    } finally {
      setIsGenerating(false)
    }
  }, [inquiry.id])

  const handleSendReply = async () => {
    const trimmedDraft = draftText.trim()

    if (!trimmedDraft || isSending) {
      return
    }

    setIsSending(true)
    setReplyError(null)

    try {
      const response = await fetch(`${getApiBaseUrl()}/api/inquiries/${inquiry.id}/replies`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ body: trimmedDraft }),
      })
      const result = (await response.json()) as InquiryReply | { message?: string }

      if (!response.ok || !result || !("body" in result)) {
        const message = result && "message" in result ? result.message : "답변 저장에 실패했습니다."
        throw new Error(message)
      }

      setSavedReplies((prev) => [...prev, result])
      setDraftText(trimmedDraft)
      setIsEditing(false)
    } catch (error) {
      setReplyError(getErrorMessage(error, "답변 저장에 실패했습니다."))
    } finally {
      setIsSending(false)
    }
  }

  useEffect(() => {
    let active = true

    async function loadReplies() {
      setIsLoadingReplies(true)
      setReplyError(null)

      try {
        const response = await fetch(`${getApiBaseUrl()}/api/inquiries/${inquiry.id}/replies`, {
          cache: "no-store",
        })
        const result = (await response.json()) as { items?: InquiryReply[]; message?: string }

        if (!response.ok || !Array.isArray(result.items)) {
          throw new Error(result.message || "저장된 답변을 불러오지 못했습니다.")
        }

        if (active) {
          setSavedReplies(result.items)
        }
      } catch (error) {
        if (active) {
          setReplyError(getErrorMessage(error, "저장된 답변을 불러오지 못했습니다."))
          setSavedReplies([])
        }
      } finally {
        if (active) {
          setIsLoadingReplies(false)
        }
      }
    }

    loadReplies()

    return () => {
      active = false
    }
  }, [inquiry.id])

  useEffect(() => {
    const initialDraft = inquiry.aiDraft ?? ""

    setDraftText(initialDraft)
    setIsEditing(false)
    setGenerateError(null)
    setReplyError(null)
    setHasGeneratedDraft(false)

    if (initialDraft.trim() || lastAutoGeneratedInquiryIdRef.current === inquiry.id) {
      return
    }

    lastAutoGeneratedInquiryIdRef.current = inquiry.id
    void handleGenerateDraft()
  }, [handleGenerateDraft, inquiry.aiDraft, inquiry.id])

  return (
    <div className="flex h-full flex-col">
      <div className="border-b border-border bg-card px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <div className="mb-1 flex items-center gap-3">
              <h1 className="text-lg font-semibold text-foreground">{inquiry.title}</h1>
              <Badge className="gap-1 border-0 bg-[oklch(0.95_0.05_25)] text-xs font-medium text-[oklch(0.55_0.15_25)]">
                <Clock className="h-3 w-3" />
                {inquiry.status === "complete" ? "완료" : "대기중"}
              </Badge>
              <Badge className="gap-1 border-0 bg-[oklch(0.92_0.05_250)] text-xs font-medium text-[oklch(0.50_0.15_250)]">
                <Tag className="h-3 w-3" />
                {inquiry.category}
              </Badge>
            </div>
            <p className="text-sm text-muted-foreground">
              {inquiry.productName} | 주문번호 {inquiry.orderNumber} | 티켓 #{inquiry.ticketNumber}
            </p>
          </div>
          <div className="flex items-center gap-2 rounded-lg bg-secondary px-3 py-1.5 text-sm text-muted-foreground">
            <Clock className="h-4 w-4" />
            <span>응답 대기시간:</span>
            <span className="font-semibold text-foreground">{inquiry.waitTime}</span>
          </div>
        </div>
      </div>

      <div className="flex-1 space-y-6 overflow-y-auto p-6">
        {inquiry.conversation.map((msg) => (
          <div key={msg.id}>
            {msg.type === "customer" ? (
              <div className="flex gap-3">
                <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-[oklch(0.55_0.15_250)]">
                  <span className="font-semibold text-white">{inquiry.customerInitial}</span>
                </div>
                <div className="flex-1">
                  <div className="mb-2 flex items-center gap-2">
                    <span className="font-medium text-foreground">{msg.name}</span>
                    <Badge className="gap-1 border-0 bg-[oklch(0.95_0.08_85)] text-xs font-medium text-[oklch(0.50_0.15_85)]">
                      <Crown className="h-3 w-3" />
                      {inquiry.customerTier}
                    </Badge>
                    <span className="text-xs text-muted-foreground">{msg.time}</span>
                  </div>
                  <div className="max-w-[85%] rounded-xl rounded-tl-sm border border-border bg-card p-4 shadow-sm">
                    <p className="leading-relaxed text-foreground">{msg.message}</p>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex justify-center">
                <div className="flex items-center gap-2 rounded-full bg-secondary px-4 py-1.5">
                  <CheckCheck className="h-3 w-3 text-[oklch(0.55_0.15_155)]" />
                  <span className="text-xs text-muted-foreground">{msg.message}</span>
                  <span className="text-xs text-muted-foreground">| {msg.time}</span>
                </div>
              </div>
            )}
          </div>
        ))}

        {isLoadingReplies ? (
          <div className="flex justify-center">
            <div className="flex items-center gap-2 rounded-full bg-secondary px-4 py-1.5 text-xs text-muted-foreground">
              <RefreshCw className="h-3 w-3 animate-spin" />
              저장된 답변을 불러오는 중입니다.
            </div>
          </div>
        ) : null}

        {savedReplies.map((reply) => (
          <div key={reply.id} className="flex justify-end">
            <div className="max-w-[78%]">
              <div className="mb-2 flex items-center justify-end gap-2">
                <span className="text-xs text-muted-foreground">{formatReplyTime(reply.createdAt)}</span>
                <Badge className="border-0 bg-[oklch(0.92_0.05_155)] text-xs font-medium text-[oklch(0.45_0.14_155)]">
                  담당자 답변
                </Badge>
              </div>
              <div className="rounded-xl rounded-br-sm bg-[oklch(0.55_0.15_250)] p-4 text-white shadow-sm">
                <p className="whitespace-pre-wrap leading-relaxed">{reply.body}</p>
              </div>
            </div>
          </div>
        ))}

        <div className="mt-8">
          <div className="rounded-xl border-2 border-[oklch(0.80_0.10_250)] bg-[oklch(0.96_0.03_250)] p-5">
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-[oklch(0.55_0.15_250)]">
                <Sparkles className="h-5 w-5 text-white" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground">AI 답변 초안</h3>
                <p className="text-xs text-muted-foreground">
                  {isGenerating ? "Gemini가 답변 초안을 생성하고 있습니다" : "스토어 정책 기반 Gemini 초안"}
                </p>
              </div>
              <Badge className="ml-auto border-0 bg-[oklch(0.92_0.05_250)] font-medium text-[oklch(0.50_0.15_250)]">
                {isGenerating ? "Gemini 생성 중" : hasGeneratedDraft ? "Gemini 생성 완료" : "초안 준비됨"}
              </Badge>
            </div>

            {isEditing ? (
              <Textarea
                value={draftText}
                onChange={(event) => setDraftText(event.target.value)}
                className="min-h-[200px] resize-none border-border bg-card text-foreground focus:ring-2 focus:ring-primary"
              />
            ) : isGenerating ? (
              <div className="rounded-lg border border-border bg-card p-4">
                <div className="flex items-center gap-3">
                  <RefreshCw className="h-4 w-4 animate-spin text-[oklch(0.55_0.15_250)]" />
                  <span className="text-sm text-foreground">답변 초안을 생성하는 중입니다...</span>
                </div>
              </div>
            ) : (
              <div className="whitespace-pre-wrap rounded-lg border border-border bg-card p-4 leading-relaxed text-foreground">
                {draftText || "아직 생성된 초안이 없습니다."}
              </div>
            )}

            {generateError ? (
              <div className="mt-4 rounded-lg border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">
                {generateError}
              </div>
            ) : null}

            {replyError ? (
              <div className="mt-4 rounded-lg border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">
                {replyError}
              </div>
            ) : null}

            <div className="mt-5 flex items-center gap-3">
              <Button
                className="gap-2 bg-[oklch(0.55_0.15_250)] px-6 text-white hover:bg-[oklch(0.50_0.15_250)]"
                onClick={handleSendReply}
                disabled={!draftText.trim() || isGenerating || isSending}
              >
                <Send className="h-4 w-4" />
                {isSending ? "저장 중..." : "답변 전송"}
              </Button>
              <Button
                variant="outline"
                className={cn("gap-2 border-border hover:bg-secondary", isEditing && "bg-secondary")}
                onClick={() => setIsEditing(!isEditing)}
                disabled={isGenerating}
              >
                <Pencil className="h-4 w-4" />
                {isEditing ? "편집 완료" : "수정하기"}
              </Button>
              <Button
                variant="outline"
                className="gap-2 border-border hover:bg-secondary"
                onClick={handleGenerateDraft}
                disabled={isGenerating}
              >
                <RefreshCw className={cn("h-4 w-4", isGenerating && "animate-spin")} />
                {isGenerating ? "생성 중..." : "다시 생성"}
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="border-t border-border bg-card p-4">
        <div className="rounded-xl bg-secondary p-4">
          <Textarea
            value={draftText}
            onChange={(event) => setDraftText(event.target.value)}
            onKeyDown={(event) => {
              if ((event.ctrlKey || event.metaKey) && event.key === "Enter") {
                event.preventDefault()
                void handleSendReply()
              }
            }}
            placeholder="직접 답변을 입력하거나 AI 초안을 수정하세요..."
            className="max-h-[120px] min-h-[60px] resize-none border-0 bg-transparent p-0 text-foreground placeholder:text-muted-foreground focus-visible:ring-0"
            disabled={isGenerating}
          />
          <div className="mt-3 flex items-center justify-between border-t border-border pt-3">
            <div className="flex items-center gap-1">
              <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:bg-card hover:text-foreground">
                <Paperclip className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:bg-card hover:text-foreground">
                <ImageIcon className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:bg-card hover:text-foreground">
                <Smile className="h-4 w-4" />
              </Button>
            </div>
            <div className="flex items-center gap-3">
              <span className="text-xs text-muted-foreground">Ctrl + Enter로 전송</span>
              <Button
                size="sm"
                className="gap-2 bg-[oklch(0.55_0.15_250)] text-white hover:bg-[oklch(0.50_0.15_250)]"
                onClick={handleSendReply}
                disabled={!draftText.trim() || isGenerating || isSending}
              >
                <Send className="h-4 w-4" />
                {isSending ? "저장 중..." : "전송"}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
